import { pagesWebpUrl } from '@/lib/pagesAssets'

export const buildingIcons: Record<string, string> = {
  empty: pagesWebpUrl("/Images/buildingIcons/empty.webp"),
  church: pagesWebpUrl("/Images/buildingIcons/church.webp"),
  empty_spawn: pagesWebpUrl("/Images/buildingIcons/empty_spawn.webp"),
  church_spawn: pagesWebpUrl("/Images/buildingIcons/church_spawn.webp"),
  fort: pagesWebpUrl("/Images/buildingIcons/fort.webp"),
  fort_magic: pagesWebpUrl("/Images/buildingIcons/fort_magic.webp"),
  greatchurch: pagesWebpUrl("/Images/buildingIcons/greatchurch.webp"),
  greatchurch_fire: pagesWebpUrl("/Images/buildingIcons/greatchurch_fire.webp"),
  greatchurch_holy: pagesWebpUrl("/Images/buildingIcons/greatchurch_holy.webp"),
  mainencampment: pagesWebpUrl("/Images/buildingIcons/mainencampment.webp"),
  mainencampment_eletric: pagesWebpUrl("/Images/buildingIcons/mainencampment_eletric.webp"),
  mainencampment_fire: pagesWebpUrl("/Images/buildingIcons/mainencampment_fire.webp"),
  mainencampment_madness: pagesWebpUrl("/Images/buildingIcons/mainencampment_madness.webp"),
  ruins: pagesWebpUrl("/Images/buildingIcons/ruins.webp"),
  ruins_bleed: pagesWebpUrl("/Images/buildingIcons/ruins_bleed.webp"),
  ruins_blight: pagesWebpUrl("/Images/buildingIcons/ruins_blight.webp"),
  ruins_eletric: pagesWebpUrl("/Images/buildingIcons/ruins_eletric.webp"),
  ruins_fire: pagesWebpUrl("/Images/buildingIcons/ruins_fire.webp"),
  ruins_frostbite: pagesWebpUrl("/Images/buildingIcons/ruins_frostbite.webp"),
  ruins_holy: pagesWebpUrl("/Images/buildingIcons/ruins_holy.webp"),
  ruins_magic: pagesWebpUrl("/Images/buildingIcons/ruins_magic.webp"),
  ruins_poison: pagesWebpUrl("/Images/buildingIcons/ruins_poison.webp"),
  ruins_sleep: pagesWebpUrl("/Images/buildingIcons/ruins_sleep.webp"),
  sorcerers: pagesWebpUrl("/Images/buildingIcons/sorcerers.webp"),
  township: pagesWebpUrl("/Images/buildingIcons/township.webp"),
}

export const buildingIconOrder: string[] = [
  "empty",
  "empty_spawn",
  "church",
  "church_spawn",
  "fort",
  "fort_magic",
  "greatchurch",
  "greatchurch_fire",
  "greatchurch_holy",
  "mainencampment",
  "mainencampment_eletric",
  "mainencampment_fire",
  "mainencampment_madness",
  "ruins",
  "ruins_bleed",
  "ruins_blight",
  "ruins_eletric",
  "ruins_fire",
  "ruins_frostbite",
  "ruins_holy",
  "ruins_magic",
  "ruins_poison",
  "ruins_sleep",
  "sorcerers",
  "township",
]

export const nightlordIcons: Record<string, string> = {
  "empty": pagesWebpUrl("/Images/nightlordIcons/empty_nightlord.webp"),
  "1_Gladius": pagesWebpUrl("/Images/nightlordIcons/1_Gladius.webp"),
  "2_Adel": pagesWebpUrl("/Images/nightlordIcons/2_Adel.webp"),
  "3_Gnoster": pagesWebpUrl("/Images/nightlordIcons/3_Gnoster.webp"),
  "4_Maris": pagesWebpUrl("/Images/nightlordIcons/4_Maris.webp"),
  "5_Libra": pagesWebpUrl("/Images/nightlordIcons/5_Libra.webp"),
  "6_Fulghor": pagesWebpUrl("/Images/nightlordIcons/6_Fulghor.webp"),
  "7_Caligo": pagesWebpUrl("/Images/nightlordIcons/7_Caligo.webp"),
  "8_Heolstor": pagesWebpUrl("/Images/nightlordIcons/8_Heolstor.webp"),
}

export const nightlordNames: Record<string, string> = {
  "1_Gladius": "Gladius",
  "2_Adel": "Adel",
  "3_Gnoster": "Gnoster",
  "4_Maris": "Maris",
  "5_Libra": "Libra",
  "6_Fulghor": "Fulghor",
  "7_Caligo": "Caligo",
  "8_Heolstor": "Heolstor",
}

export const nightlordIconOrder: string[] = [
  "1_Gladius",
  "2_Adel",
  "3_Gnoster",
  "4_Maris",
  "5_Libra",
  "6_Fulghor",
  "7_Caligo",
  "8_Heolstor",
]

export const Events: Record<string, string> = {
  augurraid: pagesWebpUrl("/Images/events/augurraid.webp"),
  extraboss: pagesWebpUrl("/Images/events/extraboss.webp"),
  fellomen: pagesWebpUrl("/Images/events/fellomen.webp"),
  frenzytower: pagesWebpUrl("/Images/events/frenzytower.webp"),
  gnosterplague: pagesWebpUrl("/Images/events/gnosterplague.webp"),
  libracurse: pagesWebpUrl("/Images/events/libracurse.webp"),
  mausoleum: pagesWebpUrl("/Images/events/mausoleum.webp"),
  meteorstrike: pagesWebpUrl("/Images/events/meteorstrike.webp"),
  nighthorde: pagesWebpUrl("/Images/events/nighthorde.webp"),
  sorcerersrise: pagesWebpUrl("/Images/events/sorcerersrise.webp"),
}