import { pagesWebpUrl } from '@/lib/pagesAssets'

export const buildingIcons: Record<string, string> = {
  empty: pagesWebpUrl("/Images/buildingIcons/empty.webp"),
  church: pagesWebpUrl("/Images/buildingIcons/church.webp"),
  empty_spawn: pagesWebpUrl("/Images/buildingIcons/empty_spawn.webp"),
  church_spawn: pagesWebpUrl("/Images/buildingIcons/church_spawn.webp"),
  forge: pagesWebpUrl("/Images/buildingIcons/forge.webp"),
  forge_bleed: pagesWebpUrl("/Images/buildingIcons/forge_bleed.webp"),
  forge_eletric: pagesWebpUrl("/Images/buildingIcons/forge_eletric.webp"),
  forge_fire: pagesWebpUrl("/Images/buildingIcons/forge_fire.webp"),
  forge_holy: pagesWebpUrl("/Images/buildingIcons/forge_holy.webp"),
  forge_poison: pagesWebpUrl("/Images/buildingIcons/forge_poison.webp"),
  fort: pagesWebpUrl("/Images/buildingIcons/fort.webp"),
  fort_magic: pagesWebpUrl("/Images/buildingIcons/fort_magic.webp"),
  greatchurch: pagesWebpUrl("/Images/buildingIcons/greatchurch.webp"),
  greatchurch_eletric: pagesWebpUrl("/Images/buildingIcons/greatchurch_eletric.webp"),
  greatchurch_fire: pagesWebpUrl("/Images/buildingIcons/greatchurch_fire.webp"),
  greatchurch_frostbite: pagesWebpUrl("/Images/buildingIcons/greatchurch_frostbite.webp"),
  greatchurch_holy: pagesWebpUrl("/Images/buildingIcons/greatchurch_holy.webp"),
  greatchurch_sleep: pagesWebpUrl("/Images/buildingIcons/greatchurch_sleep.webp"),
  mainencampment: pagesWebpUrl("/Images/buildingIcons/mainencampment.webp"),
  mainencampment_eletric: pagesWebpUrl("/Images/buildingIcons/mainencampment_eletric.webp"),
  mainencampment_fire: pagesWebpUrl("/Images/buildingIcons/mainencampment_fire.webp"),
  mainencampment_madness: pagesWebpUrl("/Images/buildingIcons/mainencampment_madness.webp"),
  marsh_bleed: pagesWebpUrl("/Images/buildingIcons/marsh_bleed.webp"),
  marsh_frostbite: pagesWebpUrl("/Images/buildingIcons/marsh_frostbite.webp"),
  marsh_madness: pagesWebpUrl("/Images/buildingIcons/marsh_madness.webp"),
  marsh_poison: pagesWebpUrl("/Images/buildingIcons/marsh_poison.webp"),
  marsh_rot: pagesWebpUrl("/Images/buildingIcons/marsh_rot.webp"),
  marsh_sleep: pagesWebpUrl("/Images/buildingIcons/marsh_sleep.webp"),
  portal: pagesWebpUrl("/Images/buildingIcons/portal.webp"),
  ruins: pagesWebpUrl("/Images/buildingIcons/ruins.webp"),
  ruins_bleed: pagesWebpUrl("/Images/buildingIcons/ruins_bleed.webp"),
  ruins_blight: pagesWebpUrl("/Images/buildingIcons/ruins_blight.webp"),
  ruins_eletric: pagesWebpUrl("/Images/buildingIcons/ruins_eletric.webp"),
  ruins_fire: pagesWebpUrl("/Images/buildingIcons/ruins_fire.webp"),
  ruins_frostbite: pagesWebpUrl("/Images/buildingIcons/ruins_frostbite.webp"),
  ruins_holy: pagesWebpUrl("/Images/buildingIcons/ruins_holy.webp"),
  ruins_magic: pagesWebpUrl("/Images/buildingIcons/ruins_magic.webp"),
  ruins_poison: pagesWebpUrl("/Images/buildingIcons/ruins_poison.webp"),
  ruins_sleep: pagesWebpUrl("/Images/buildingIcons/ruins_sleep.webp"),
  sorcerers: pagesWebpUrl("/Images/buildingIcons/sorcerers.webp"),
  township: pagesWebpUrl("/Images/buildingIcons/township.webp"),
  EUF_holy: pagesWebpUrl("/Images/buildingIcons/EUF_holy.webp"),
  EUF_rot: pagesWebpUrl("/Images/buildingIcons/EUF_rot.webp"),
  WUF_fire: pagesWebpUrl("/Images/buildingIcons/WUF_fire.webp"),
  WUF_magic: pagesWebpUrl("/Images/buildingIcons/WUF_magic.webp"),
}

export const buildingIconOrder: string[] = [
  "empty",
  "empty_spawn",
  "church",
  "church_spawn",
  "forge",
  "forge_bleed",
  "forge_eletric",
  "forge_fire",
  "forge_holy",
  "forge_poison",
  "fort",
  "fort_magic",
  "greatchurch",
  "greatchurch_eletric",
  "greatchurch_fire",
  "greatchurch_frostbite",
  "greatchurch_holy",
  "greatchurch_sleep",
  "mainencampment",
  "mainencampment_eletric",
  "mainencampment_fire",
  "mainencampment_madness",
  "marsh_bleed",
  "marsh_frostbite",
  "marsh_madness",
  "marsh_poison",
  "marsh_rot",
  "marsh_sleep",
  "portal",
  "ruins",
  "ruins_bleed",
  "ruins_blight",
  "ruins_eletric",
  "ruins_fire",
  "ruins_frostbite",
  "ruins_holy",
  "ruins_magic",
  "ruins_poison",
  "ruins_sleep",
  "sorcerers",
  "township",
  "EUF_holy",
  "EUF_rot",
  "WUF_fire",
  "WUF_magic",
]

export const nightlordIcons: Record<string, string> = {
  "empty": pagesWebpUrl("/Images/nightlordIcons/empty_nightlord.webp"),
  "1_Gladius": pagesWebpUrl("/Images/nightlordIcons/1_Gladius.webp"),
  "2_Adel": pagesWebpUrl("/Images/nightlordIcons/2_Adel.webp"),
  "3_Gnoster": pagesWebpUrl("/Images/nightlordIcons/3_Gnoster.webp"),
  "4_Maris": pagesWebpUrl("/Images/nightlordIcons/4_Maris.webp"),
  "5_Libra": pagesWebpUrl("/Images/nightlordIcons/5_Libra.webp"),
  "6_Fulghor": pagesWebpUrl("/Images/nightlordIcons/6_Fulghor.webp"),
  "7_Caligo": pagesWebpUrl("/Images/nightlordIcons/7_Caligo.webp"),
  "8_Heolstor": pagesWebpUrl("/Images/nightlordIcons/8_Heolstor.webp"),
  "9_Balancers": pagesWebpUrl("/Images/nightlordIcons/9_Balancers.webp"),
  "10_Greg": pagesWebpUrl("/Images/nightlordIcons/10_Greg.webp"),
}

export const nightlordNames: Record<string, string> = {
  "1_Gladius": "Gladius",
  "2_Adel": "Adel",
  "3_Gnoster": "Gnoster",
  "4_Maris": "Maris",
  "5_Libra": "Libra",
  "6_Fulghor": "Fulghor",
  "7_Caligo": "Caligo",
  "8_Heolstor": "Heolstor",
  "9_Balancers": "Balancers",
  "10_Greg": "Greg",
}

export const nightlordIconOrder: string[] = [
  "1_Gladius",
  "2_Adel",
  "3_Gnoster",
  "4_Maris",
  "5_Libra",
  "6_Fulghor",
  "7_Caligo",
  "8_Heolstor",
  "9_Balancers",
  "10_Greg",
]

export const nightlordStatusCards: Record<string, string> = {
  "1_Gladius": pagesWebpUrl("/Images/nightlordStatus/1_Gladius_Status.webp"),
  "2_Adel": pagesWebpUrl("/Images/nightlordStatus/2_Adel_Status.webp"),
  "3_Gnoster": pagesWebpUrl("/Images/nightlordStatus/3_Gnoster_Status.webp"),
  "4_Maris": pagesWebpUrl("/Images/nightlordStatus/4_Maris_Status.webp"),
  "5_Libra": pagesWebpUrl("/Images/nightlordStatus/5_Libra_Status.webp"),
  "6_Fulghor": pagesWebpUrl("/Images/nightlordStatus/6_Fulghor_Status.webp"),
  "7_Caligo": pagesWebpUrl("/Images/nightlordStatus/7_Caligo_Status.webp"),
  "8_Heolstor": pagesWebpUrl("/Images/nightlordStatus/8_Heolstor_Status.webp"),
  "9_Balancers": pagesWebpUrl("/Images/nightlordStatus/9_Balancers_Status.webp"),
  "10_Greg": pagesWebpUrl("/Images/nightlordStatus/10_Greg_Status.webp"),
}

export const Events: Record<string, string> = {
  augurraid: pagesWebpUrl("/Images/events/augurraid.webp"),
  balancersRaid: pagesWebpUrl("/Images/events/balancersRaid.webp"),
  caligoRaid: pagesWebpUrl("/Images/events/caligoRaid.webp"),
  extraboss: pagesWebpUrl("/Images/events/extraboss.webp"),
  fellomen: pagesWebpUrl("/Images/events/fellomen.webp"),
  frenzytower: pagesWebpUrl("/Images/events/frenzytower.webp"),
  gladiusRaid: pagesWebpUrl("/Images/events/gladiusRaid.webp"),
  gnosterplague: pagesWebpUrl("/Images/events/gnosterplague.webp"),
  libracurse: pagesWebpUrl("/Images/events/libracurse.webp"),
  mausoleum: pagesWebpUrl("/Images/events/mausoleum.webp"),
  meteorstrike: pagesWebpUrl("/Images/events/meteorstrike.webp"),
  nighthorde: pagesWebpUrl("/Images/events/nighthorde.webp"),
  sorcerersrise: pagesWebpUrl("/Images/events/sorcerersrise.webp"),
}