export const buildingIcons: Record<string, string> = {
  empty: "/Images/buildingIcons/empty.webp",
  church: "/Images/buildingIcons/church.webp",
  fort: "/Images/buildingIcons/fort.webp",
  fort_magic: "/Images/buildingIcons/fort_magic.webp",
  greatchurch: "/Images/buildingIcons/greatchurch.webp",
  greatchurch_fire: "/Images/buildingIcons/greatchurch_fire.webp",
  greatchurch_holy: "/Images/buildingIcons/greatchurch_holy.webp",
  mainencampment: "/Images/buildingIcons/mainencampment.webp",
  mainencampment_eletric: "/Images/buildingIcons/mainencampment_eletric.webp",
  mainencampment_fire: "/Images/buildingIcons/mainencampment_fire.webp",
  mainencampment_madness: "/Images/buildingIcons/mainencampment_madness.webp",
  ruins: "/Images/buildingIcons/ruins.webp",
  ruins_bleed: "/Images/buildingIcons/ruins_bleed.webp",
  ruins_blight: "/Images/buildingIcons/ruins_blight.webp",
  ruins_eletric: "/Images/buildingIcons/ruins_eletric.webp",
  ruins_fire: "/Images/buildingIcons/ruins_fire.webp",
  ruins_frostbite: "/Images/buildingIcons/ruins_frostbite.webp",
  ruins_holy: "/Images/buildingIcons/ruins_holy.webp",
  ruins_magic: "/Images/buildingIcons/ruins_magic.webp",
  ruins_poison: "/Images/buildingIcons/ruins_poison.webp",
  ruins_sleep: "/Images/buildingIcons/ruins_sleep.webp",
  sorcerers: "/Images/buildingIcons/sorcerers.webp",
  township: "/Images/buildingIcons/township.webp",
};
export const buildingIconOrder: string[] = [
  "empty",
  "church",
  "fort",
  "fort_magic",
  "greatchurch",
  "greatchurch_fire",
  "greatchurch_holy",
  "mainencampment",
  "mainencampment_eletric",
  "mainencampment_fire",
  "mainencampment_madness",
  "ruins",
  "ruins_bleed",
  "ruins_blight",
  "ruins_eletric",
  "ruins_fire",
  "ruins_frostbite",
  "ruins_holy",
  "ruins_magic",
  "ruins_poison",
  "ruins_sleep",
  "sorcerers",
  "township",
];
export const nightlordIcons: Record<string, string> = {
  "1_Gladius": "/Images/nightlordIcons/1_Gladius.webp",
  "2_Adel": "/Images/nightlordIcons/2_Adel.webp",
  "3_Gnoster": "/Images/nightlordIcons/3_Gnoster.webp",
  "4_Maris": "/Images/nightlordIcons/4_Maris.webp",
  "5_Libra": "/Images/nightlordIcons/5_Libra.webp",
  "6_Fulghor": "/Images/nightlordIcons/6_Fulghor.webp",
  "7_Caligo": "/Images/nightlordIcons/7_Caligo.webp",
  "8_Heolstor": "/Images/nightlordIcons/8_Heolstor.webp",
};
export const nightlordNames: Record<string, string> = {
  "1_Gladius": "Gladius",
  "2_Adel": "Adel",
  "3_Gnoster": "Gnoster",
  "4_Maris": "Maris",
  "5_Libra": "Libra",
  "6_Fulghor": "Fulghor",
  "7_Caligo": "Caligo",
  "8_Heolstor": "Heolstor",
};
export const nightlordIconOrder: string[] = [
  "1_Gladius",
  "2_Adel",
  "3_Gnoster",
  "4_Maris",
  "5_Libra",
  "6_Fulghor",
  "7_Caligo",
  "8_Heolstor",
];
export const Events: Record<string, string> = {
  augurraid: "/Images/events/augurraid.webp",
  extraboss: "/Images/events/extraboss.webp",
  fellomen: "/Images/events/fellomen.webp",
  frenzytower: "/Images/events/frenzytower.webp",
  gnosterplague: "/Images/events/gnosterplague.webp",
  libracurse: "/Images/events/libracurse.webp",
  mausoleum: "/Images/events/mausoleum.webp",
  meteorstrike: "/Images/events/meteorstrike.webp",
  nighthorde: "/Images/events/nighthorde.webp",
  sorcerersrise: "/Images/events/sorcerersrise.webp",
};